### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by ivangodfather** [hughbe/day-date-picker#1]
Hello, the demo uplaoded seems not working,

```
[self.picker setup]; //3: CALL - [DayDatePickerView setup] (NOT optional)
```

This method doesnt exist, can you fix it? Thx you. Great work!

**Comment by hughbe** [comment]
Hi,
Thanks for the message.
The setup function is called automatically when you init the view with a frame or load it from a storyboard/xib file.
However, if you want to call it manually, I have updated the header file for DayDatePicker.h in the latest commit to fix your issue.

Thanksk
