### ISSUE TITLE
Ability to customise background color

### ISSUE THREAD

**Issue by markst** [hughbe/day-date-picker#16]
For example, I'd like to style the picker to look like consistent with default `UIPicker`

![simulator screen shot - ipad 6th generation - 2018-11-26 at 14 52 42](https://user-images.githubusercontent.com/274318/48992260-f7cd2e00-f18a-11e8-939b-0b0525af7d6e.png)

**Comment by markst** [comment]
Ah guess I can change the overlay as follows:
```swift
datePicker.overlayView.backgroundColor = UIColor.clear
datePicker.overlayView.layer.borderWidth = 0.5
datePicker.overlayView.layer.borderColor = UIColor.gray.cgColor
```

**Comment by hughbe** [comment]
Fixed
