### ISSUE TITLE
Year is wrong

### ISSUE THREAD

**Issue by ivangodfather** [hughbe/day-date-picker#2]
If you move the year , instead of 2015-2016 it shows 2017, its little buggy, plus it will be much better if it has all the previous years. (like for selecting a birthday). Or at least has the option.

**Comment by robdigital** [comment]
I have fixed this issue where 2016 jumps to 2017 in my fork https://github.com/robdigital/DayDatePicker

**Comment by hughbe** [comment]
This issue has been fixed owing to the latest pull request. Thank you
