### ISSUE TITLE
date not showing in the label

### ISSUE THREAD

**Issue by ouerghemmi** [hughbe/day-date-picker#4]
![capture1](https://cloud.githubusercontent.com/assets/2032472/8517304/72c7ebfe-23b7-11e5-90d4-2ae93e326d01.png)
![capture2](https://cloud.githubusercontent.com/assets/2032472/8517305/72c8b002-23b7-11e5-9ea7-feccde474392.png)

Hi, 

How to get date in the label of the highlighted date in the picker (in the middle) in the demo? 

i need that picker.date will be updated once the row changes. i tried : 
    [self dayDatePickerView:self.picker didSelectDate:self.picker.date];

but it returns wrong date !

There is a way to fix this issue please? 

Thanks

**Comment by robdigital** [comment]
I believe i have fixed your problem in my fork here https://github.com/robdigital/DayDatePicker
Please let me know if this works for you.

**Comment by hughbe** [comment]
Updated the main fork with this bug fix. Thank you.
