### ISSUE TITLE
Max date?

### ISSUE THREAD

**Issue by holidaycottages** [hughbe/day-date-picker#5]
Could you implement a max date feature?

So you can stop the calendar from going too far in the future?

**Comment by robdigital** [comment]
I have implemented a max date now in my fork https://github.com/robdigital/DayDatePicker
You should set the min / max in the view controller for best results.
let me know if you find any issues.

**Comment by hughbe** [comment]
This issue has been fixed in the latest pull request. Please download the code update to gain this functionality.
Again, thanks to @robdigital for this providing this feature
