### ISSUE TITLE
日期选中的error

### ISSUE THREAD

**Issue by shenshangjimiaoZG** [hughbe/day-date-picker#8]
选中某一天，显示前一天的日期，例如我选中23号，显示却是22号的日期

**Comment by hughbe** [comment]
Sorry could you translate this into English? Thanks

**Comment by shenshangjimiaoZG** [comment]
Selected one day, according to the previous day's date, I selected 23, for example, the date of the show is 22  @hughbe

**Comment by shenshangjimiaoZG** [comment]
![2016-04-25 17 29 29](https://cloud.githubusercontent.com/assets/3032136/14779581/58e74edc-0b0b-11e6-9339-e1f2e43d0457.png)
choose 30 ,but show 29
